export const enum MINIGAME_TYPE {
    MONEY = 1,
    BOX = 2,
    DRILL = 3,
    WIRES = 4,
    SVARKA = 5,
    HAMMER = 6,
    ORANGE = 7,
    SCISSORS = 8,
    WATERPOT = 9,
    WINDOW   = 10,
    BOX_GRASS  = 11,
    SCISSORS_GRASS = 12,
    GRASS = 13,
    COLLECT_GAME = 14,
    JAILHAMMER = 15,
    JAILSEWING = 16,
    JAILWASHING = 17,
    JAILCOOKING = 18,
    JAILTOILET = 19,
}